export const sharedStyles = {
  page: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column" as const,
    backgroundColor: "#ffffff",
  },
  main: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    padding: "2rem",
    maxWidth: "1200px",
    width: "100%",
    margin: "0 auto",
    gap: "2rem",
  },
  header: {
    width: "100%",
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
    alignItems: "flex-start",
    marginBottom: "1rem",
    "@media (min-width: 640px)": {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "1.5rem",
    },
  },
  title: {
    fontSize: "2rem",
    fontWeight: 700,
    margin: 0,
    fontFamily: "var(--font-geist-mono)",
    letterSpacing: "-0.03em",
    "@media (min-width: 640px)": {
      fontSize: "2rem",
    },
    "@media (min-width: 768px)": {
      fontSize: "2.5rem",
    },
  },
  subtitle: {
    fontSize: "1.1rem",
    color: "#444",
    margin: 0,
    fontFamily: "var(--font-geist-sans)",
    "@media (min-width: 640px)": {
      fontSize: "1.1rem",
    },
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "1rem",
    width: "100%",
    "@media (min-width: 640px)": {
      gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))",
      gap: "1.5rem",
    },
    "@media (min-width: 768px)": {
      gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
      gap: "2rem",
    },
  },
  card: {
    border: "1px solid #eaeaea",
    borderRadius: "8px",
    padding: "1rem",
    transition: "all 0.2s ease",
    cursor: "pointer",
    backgroundColor: "#fff",
    width: "100%",
    "@media (min-width: 640px)": {
      padding: "1.25rem",
    },
    "@media (min-width: 768px)": {
      padding: "1.5rem",
      "&:hover": {
        transform: "translateY(-2px)",
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  button: {
    width: "100%",
    height: "2.5rem",
    padding: "0 1.25rem",
    backgroundColor: "#000",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    fontSize: "0.9rem",
    cursor: "pointer",
    fontFamily: "var(--font-geist-sans)",
    transition: "background-color 0.2s",
    touchAction: "manipulation",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    whiteSpace: "nowrap",
    "@media (min-width: 640px)": {
      width: "auto",
      fontSize: "1rem",
    },
    "&:hover": {
      backgroundColor: "#333",
    },
    "&:active": {
      backgroundColor: "#444",
    },
  },
  secondaryButton: {
    width: "100%",
    height: "2.5rem",
    padding: "0 1.25rem",
    backgroundColor: "#fff",
    color: "#000",
    border: "2px solid #000",
    borderRadius: "4px",
    fontSize: "0.9rem",
    cursor: "pointer",
    fontFamily: "var(--font-geist-sans)",
    transition: "all 0.2s",
    touchAction: "manipulation",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    whiteSpace: "nowrap",
    "@media (min-width: 640px)": {
      width: "auto",
      fontSize: "1rem",
    },
    "&:hover": {
      backgroundColor: "#000",
      color: "#fff",
    },
    "&:active": {
      backgroundColor: "#333",
      borderColor: "#333",
    },
  },
  input: {
    padding: "0.75rem 1rem",
    border: "2px solid #000",
    borderRadius: "4px",
    fontSize: "0.9rem",
    width: "100%",
    fontFamily: "var(--font-geist-sans)",
    transition: "border-color 0.2s",
    outline: "none",
    "@media (min-width: 640px)": {
      fontSize: "1rem",
      padding: "0.8rem 1rem",
    },
    "&:focus": {
      borderColor: "#666",
    },
  },
  form: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
    width: "100%",
    maxWidth: "100%",
    "@media (min-width: 640px)": {
      maxWidth: "500px",
    },
  },
  error: {
    color: "#dc2626",
    fontSize: "0.9rem",
    margin: 0,
    fontFamily: "var(--font-geist-sans)",
    "@media (min-width: 640px)": {
      fontSize: "0.9rem",
    },
  },
  success: {
    color: "#00cc66",
    fontSize: "0.85rem",
    margin: 0,
    fontFamily: "var(--font-geist-sans)",
    "@media (min-width: 640px)": {
      fontSize: "0.9rem",
    },
  },
  footer: {
    padding: "1rem",
    textAlign: "center" as const,
    borderTop: "1px solid #eaeaea",
    "@media (min-width: 640px)": {
      padding: "1.5rem",
    },
    "@media (min-width: 768px)": {
      padding: "2rem",
    },
  },
  link: {
    color: "#444",
    textDecoration: "none",
    fontFamily: "var(--font-geist-sans)",
    transition: "color 0.2s",
    padding: "0.5rem",
    display: "inline-block",
    "&:hover": {
      color: "#000",
    },
  },
  nav: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.75rem",
    alignItems: "stretch",
    width: "100%",
    "@media (min-width: 640px)": {
      flexDirection: "row",
      gap: "1rem",
      alignItems: "center",
      width: "auto",
    },
  },
  breadcrumbs: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "0.5rem",
    alignItems: "center",
    fontSize: "0.9rem",
    color: "#666",
    marginBottom: "1.5rem",
    padding: "0.75rem",
    backgroundColor: "#f5f5f5",
    borderRadius: "4px",
    overflowX: "auto" as const,
    "@media (min-width: 640px)": {
      marginBottom: "2rem",
      padding: "1rem",
    },
  },
  separator: {
    color: "#666",
    userSelect: "none" as const,
  },
}; 